const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const estado={menu:[],entidades:[],clientes:null,formulario:null,seleccion:'Listado'};
function hashTexto(t){let h=0;for(const c of t)h=c.charCodeAt(0)+((h<<5)-h);return Math.abs(h)}
function colorTexto(t){return `hsl(${hashTexto(t)%360},55%,45%)`}
async function cargarJSON(url){const r=await fetch(url);if(!r.ok)throw new Error(url);return r.json()}
function ficha(el,texto){el.querySelector('.ficha').textContent=texto.charAt(0).toUpperCase();el.querySelector('.ficha').style.background=colorTexto(texto);el.querySelector('.etiqueta').textContent=texto}
function renderMenu(){const c=$('#navegacion .contenido-columna');c.innerHTML='';estado.menu.forEach((x,i)=>{const n=$('#tpl-nav').content.cloneNode(true);const a=n.querySelector('a');ficha(a,x.texto);a.classList.toggle('activo',!!x.activo);a.dataset.indice=i;a.addEventListener('click',e=>{e.preventDefault();$$('#navegacion a').forEach(z=>z.classList.remove('activo'));a.classList.add('activo');mostrarTabla()});c.appendChild(n)})}
function renderEntidades(){const c=$('#entidades .contenido-columna');c.innerHTML='';estado.entidades.forEach((x,i)=>{const n=$('#tpl-card').content.cloneNode(true);const a=n.querySelector('article');ficha(a,x.texto);a.classList.toggle('activo',x.texto===estado.seleccion);a.dataset.indice=i;a.addEventListener('click',()=>{estado.seleccion=x.texto;renderEntidades();x.texto==='Elemento'||x.texto==='Formulario'?mostrarFormularioUI():x.texto==='Login'?mostrarLoginDemo():x.texto==='Toasts'?mostrarToastsDemo():mostrarTabla()});a.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',x.texto));c.appendChild(n)})}
function mostrarTabla(filtro=''){const d=estado.clientes;const regs=d.registros.filter(r=>Object.values(r).join(' ').toLowerCase().includes(filtro.toLowerCase()));const div=$('#escenario');div.innerHTML='';const tabla=document.createElement('table');tabla.innerHTML=`<caption>${d.titulo}</caption><thead><tr>${d.columnas.map(c=>`<th>${c.etiqueta}</th>`).join('')}</tr></thead><tbody></tbody><tfoot><tr><th colspan="${Math.max(1,d.columnas.length-1)}">Total</th><td>${regs.length}</td></tr></tfoot>`;const tb=tabla.querySelector('tbody');regs.forEach(r=>{const tr=$('#tpl-fila').content.cloneNode(true).querySelector('tr');d.columnas.forEach(c=>{const td=document.createElement('td');td.textContent=r[c.campo]??'';tr.appendChild(td)});tb.appendChild(tr)});div.appendChild(tabla)}
async function mostrarFormulario(){const cfg=estado.formulario;const div=$('#escenario');div.innerHTML='<div class="panel"><h2>Nuevo cliente</h2><form class="formulario-dinamico"><div class="campos"></div><div class="acciones"><button type="submit">Guardar</button><button type="reset">Limpiar</button></div></form></div>';const campos=div.querySelector('.campos');cfg.campos.forEach(c=>{const g=document.createElement('label');g.className='campo';const t=document.createElement('span');t.textContent=c.etiqueta;g.appendChild(t);let control;if(c.tipo==='textarea')control=document.createElement('textarea');else if(c.tipo==='select'){control=document.createElement('select');(c.opciones||[]).forEach(o=>control.add(new Option(o,o)))}else{control=document.createElement('input');control.type=c.tipo||'text'}control.name=c.nombre;g.appendChild(control);campos.appendChild(g)});div.querySelector('form').addEventListener('submit',e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(e.currentTarget));alert('Evento submit capturado\n'+JSON.stringify(fd,null,2))})}
function activarColumnas(){
  $$('.minimizar').forEach(b=>{const col=b.closest('nav,section');col.dataset.ancho=col.getBoundingClientRect().width;b.addEventListener('click',()=>{if(col.classList.contains('compacto')){const ancho=parseFloat(col.dataset.ancho)||250;col.classList.remove('compacto');col.style.flexBasis=ancho+'px';col.style.width=ancho+'px';b.textContent='◀'}else{col.dataset.ancho=col.getBoundingClientRect().width;col.style.flexBasis=col.dataset.ancho+'px';col.style.width=col.dataset.ancho+'px';void col.offsetWidth;col.classList.add('compacto');b.textContent='▶'}})});
  $$('.separador').forEach(sep=>{sep.addEventListener('pointerdown',e=>{e.preventDefault();const col=sep.previousElementSibling;if(!col||col.classList.contains('compacto'))return;const inicio=e.clientX,ancho=col.getBoundingClientRect().width;col.style.transition='none';document.body.classList.add('redimensionando');sep.setPointerCapture(e.pointerId);const mover=ev=>{const nuevo=Math.min(600,Math.max(100,ancho+ev.clientX-inicio));col.style.width=nuevo+'px';col.style.flexBasis=nuevo+'px';col.dataset.ancho=nuevo};const terminar=()=>{sep.removeEventListener('pointermove',mover);col.style.transition='';document.body.classList.remove('redimensionando')};sep.addEventListener('pointermove',mover);sep.addEventListener('pointerup',terminar,{once:true});sep.addEventListener('pointercancel',terminar,{once:true})})})
}
function toast(tipo='info',titulo='Información',texto='Operación realizada'){let stack=$('#toastStack');if(!stack){stack=document.createElement('div');stack.id='toastStack';stack.className='ju-toast-stack';document.body.appendChild(stack)}const iconos={success:'✓',info:'i',warning:'!',danger:'×'};const t=document.createElement('article');t.className=`ju-toast is-${tipo}`;t.innerHTML=`<div class="ju-toast-icon">${iconos[tipo]||'i'}</div><div><p class="ju-toast-title">${titulo}</p><p class="ju-toast-text">${texto}</p></div><button class="ju-toast-close" type="button">×</button>`;const cerrar=()=>{t.classList.add('is-leaving');setTimeout(()=>t.remove(),240)};t.querySelector('button').onclick=cerrar;stack.appendChild(t);setTimeout(cerrar,5000)}
function mostrarFormularioUI(){const div=$('#escenario');div.innerHTML=`<article class="ju-card"><h2>Librería · Formularios</h2><p>Controles reutilizables con el lenguaje visual jocarsa-iu.</p><form id="demoForm" class="ju-form-grid"><label><span>Nombre</span><input name="nombre" required></label><label><span>Email</span><input name="email" type="email" required></label><label><span>Tipo</span><select name="tipo"><option>Cliente</option><option>Proveedor</option><option>Alumno</option></select></label><label><span>Fecha</span><input name="fecha" type="date"></label><label class="ju-form-full"><span>Descripción</span><textarea name="descripcion"></textarea></label><label class="ju-check ju-form-full"><input type="checkbox" name="activo"><span>Registro activo</span></label><div class="ju-form-full ju-button-row"><button class="ju-btn" type="submit">Guardar</button><button class="ju-btn secondary" type="reset">Limpiar</button></div></form></article>`;$('#demoForm').onsubmit=e=>{e.preventDefault();toast('success','Formulario guardado','El evento submit se ha capturado correctamente.')}}
function mostrarLoginDemo(){const div=$('#escenario');div.innerHTML=`<div class="ju-login-layout" style="margin:auto"><article class="ju-login-side"><div class="ju-login-brand"><img src="https://static.jocarsa.com/logos/white.svg" alt=""><h1 class="ju-login-product-title">jocarsa | interfaz integrada</h1><p>Pantalla de acceso basada en jocarsa-iu.</p></div></article><article class="ju-login-card"><h2>Iniciar sesión</h2><form id="loginDemo" class="ju-form-grid"><label class="ju-form-full"><span>Email</span><input type="email" required></label><label class="ju-form-full"><span>Contraseña</span><input type="password" required></label><label class="ju-check ju-form-full"><input type="checkbox"><span>Mantener sesión</span></label><div class="ju-form-full ju-login-actions"><button class="ju-btn">Entrar</button><a class="ju-text-link" href="login.html">Abrir pantalla completa</a></div></form></article></div>`;$('#loginDemo').onsubmit=e=>{e.preventDefault();toast('success','Acceso simulado','Login capturado como componente reutilizable.')}}
function mostrarToastsDemo(){const div=$('#escenario');div.innerHTML=`<article class="ju-card"><h2>Librería · Toasts</h2><p>Mensajes emergentes reutilizables con autocierre y cierre manual.</p><div class="ju-button-row"><button class="ju-btn" data-t="success">Éxito</button><button class="ju-btn secondary" data-t="info">Información</button><button class="ju-btn secondary" data-t="warning">Aviso</button><button class="ju-btn secondary" data-t="danger">Error</button></div></article>`;div.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>toast(b.dataset.t,{success:'Correcto',info:'Información',warning:'Revisar',danger:'Error'}[b.dataset.t],'Ejemplo de mensaje emergente de la librería.'))}
function activarEventos(){ $('#buscador').addEventListener('input',e=>mostrarTabla(e.target.value));$('#nuevo').addEventListener('click',()=>{estado.seleccion='Elemento';renderEntidades();mostrarFormularioUI()});const esc=$('#escenario');esc.addEventListener('dragover',e=>{e.preventDefault();esc.classList.add('drag-over')});esc.addEventListener('dragleave',()=>esc.classList.remove('drag-over'));esc.addEventListener('drop',e=>{e.preventDefault();esc.classList.remove('drag-over');const vista=e.dataTransfer.getData('text/plain');estado.seleccion=vista;renderEntidades();vista==='Elemento'||vista==='Formulario'?mostrarFormularioUI():vista==='Login'?mostrarLoginDemo():vista==='Toasts'?mostrarToastsDemo():mostrarTabla()});document.addEventListener('keydown',e=>{if(e.key==='Escape')mostrarTabla()})}
async function iniciar(){try{[estado.menu,estado.entidades,estado.clientes,estado.formulario]=await Promise.all([cargarJSON('data/menu.json'),cargarJSON('data/entidades.json'),cargarJSON('data/clientes.json'),cargarJSON('data/datos.json')]);renderMenu();renderEntidades();mostrarTabla();activarColumnas();activarEventos()}catch(e){$('#escenario').innerHTML=`<div class="panel"><h2>No se pudieron cargar los orígenes de datos</h2><p>Sirve esta carpeta mediante HTTP, por ejemplo: <code>python3 -m http.server 8000</code></p><pre>${e}</pre></div>`}}
document.addEventListener('DOMContentLoaded',iniciar);
