const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const estado={menu:[],entidades:[],clientes:null,formulario:null,seleccion:'Listado'};
function hashTexto(t){let h=0;for(const c of t)h=c.charCodeAt(0)+((h<<5)-h);return Math.abs(h)}
function colorTexto(t){return `hsl(${hashTexto(t)%360},55%,45%)`}
async function cargarJSON(url){const r=await fetch(url);if(!r.ok)throw new Error(url);return r.json()}
function ficha(el,texto){el.querySelector('.ficha').textContent=texto.charAt(0).toUpperCase();el.querySelector('.ficha').style.background=colorTexto(texto);el.querySelector('.etiqueta').textContent=texto}
function renderMenu(){const c=$('#navegacion .contenido-columna');c.innerHTML='';estado.menu.forEach((x,i)=>{const n=$('#tpl-nav').content.cloneNode(true);const a=n.querySelector('a');ficha(a,x.texto);a.classList.toggle('activo',!!x.activo);a.dataset.indice=i;a.addEventListener('click',e=>{e.preventDefault();$$('#navegacion a').forEach(z=>z.classList.remove('activo'));a.classList.add('activo');mostrarTabla()});c.appendChild(n)})}
function renderEntidades(){const c=$('#entidades .contenido-columna');c.innerHTML='';estado.entidades.forEach((x,i)=>{const n=$('#tpl-card').content.cloneNode(true);const a=n.querySelector('article');ficha(a,x.texto);a.classList.toggle('activo',x.texto===estado.seleccion);a.dataset.indice=i;a.addEventListener('click',()=>{estado.seleccion=x.texto;renderEntidades();x.texto==='Elemento'?mostrarFormulario():mostrarTabla()});a.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',x.texto));c.appendChild(n)})}
function mostrarTabla(filtro=''){const d=estado.clientes;const regs=d.registros.filter(r=>Object.values(r).join(' ').toLowerCase().includes(filtro.toLowerCase()));const div=$('#escenario');div.innerHTML='';const tabla=document.createElement('table');tabla.innerHTML=`<caption>${d.titulo}</caption><thead><tr>${d.columnas.map(c=>`<th>${c.etiqueta}</th>`).join('')}</tr></thead><tbody></tbody><tfoot><tr><th colspan="${Math.max(1,d.columnas.length-1)}">Total</th><td>${regs.length}</td></tr></tfoot>`;const tb=tabla.querySelector('tbody');regs.forEach(r=>{const tr=$('#tpl-fila').content.cloneNode(true).querySelector('tr');d.columnas.forEach(c=>{const td=document.createElement('td');td.textContent=r[c.campo]??'';tr.appendChild(td)});tb.appendChild(tr)});div.appendChild(tabla)}
async function mostrarFormulario(){const cfg=estado.formulario;const div=$('#escenario');div.innerHTML='<div class="panel"><h2>Nuevo cliente</h2><form class="formulario-dinamico"><div class="campos"></div><div class="acciones"><button type="submit">Guardar</button><button type="reset">Limpiar</button></div></form></div>';const campos=div.querySelector('.campos');cfg.campos.forEach(c=>{const g=document.createElement('label');g.className='campo';const t=document.createElement('span');t.textContent=c.etiqueta;g.appendChild(t);let control;if(c.tipo==='textarea')control=document.createElement('textarea');else if(c.tipo==='select'){control=document.createElement('select');(c.opciones||[]).forEach(o=>control.add(new Option(o,o)))}else{control=document.createElement('input');control.type=c.tipo||'text'}control.name=c.nombre;g.appendChild(control);campos.appendChild(g)});div.querySelector('form').addEventListener('submit',e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(e.currentTarget));alert('Evento submit capturado\n'+JSON.stringify(fd,null,2))})}
function activarColumnas(){$$('.minimizar').forEach(b=>b.addEventListener('click',()=>{const col=b.closest('nav,section');col.classList.toggle('compacto');b.textContent=col.classList.contains('compacto')?'▶':'◀'}));$$('.separador').forEach(s=>{let inicio=null,ancho=0,col=null;s.addEventListener('pointerdown',e=>{col=document.getElementById(s.dataset.left);inicio=e.clientX;ancho=col.getBoundingClientRect().width;s.setPointerCapture(e.pointerId)});s.addEventListener('pointermove',e=>{if(inicio===null)return;col.style.width=Math.max(58,ancho+e.clientX-inicio)+'px'});s.addEventListener('pointerup',()=>inicio=null)})}
function activarEventos(){ $('#buscador').addEventListener('input',e=>mostrarTabla(e.target.value));$('#nuevo').addEventListener('click',()=>{estado.seleccion='Elemento';renderEntidades();mostrarFormulario()});const esc=$('#escenario');esc.addEventListener('dragover',e=>{e.preventDefault();esc.classList.add('drag-over')});esc.addEventListener('dragleave',()=>esc.classList.remove('drag-over'));esc.addEventListener('drop',e=>{e.preventDefault();esc.classList.remove('drag-over');const vista=e.dataTransfer.getData('text/plain');estado.seleccion=vista;renderEntidades();vista==='Elemento'?mostrarFormulario():mostrarTabla()});document.addEventListener('keydown',e=>{if(e.key==='Escape')mostrarTabla()})}
async function iniciar(){try{[estado.menu,estado.entidades,estado.clientes,estado.formulario]=await Promise.all([cargarJSON('data/menu.json'),cargarJSON('data/entidades.json'),cargarJSON('data/clientes.json'),cargarJSON('data/datos.json')]);renderMenu();renderEntidades();mostrarTabla();activarColumnas();activarEventos()}catch(e){$('#escenario').innerHTML=`<div class="panel"><h2>No se pudieron cargar los orígenes de datos</h2><p>Sirve esta carpeta mediante HTTP, por ejemplo: <code>python3 -m http.server 8000</code></p><pre>${e}</pre></div>`}}
document.addEventListener('DOMContentLoaded',iniciar);
